/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Steven
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Image geticonImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("image/logo.png"));
        return retValue;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        Contraseña2 = new javax.swing.JLabel();
        User2 = new javax.swing.JLabel();
        User1 = new javax.swing.JTextField();
        Password1 = new javax.swing.JPasswordField();
        Login = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo_1.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 270));

        Contraseña2.setBackground(new java.awt.Color(0, 0, 0));
        Contraseña2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Contraseña2.setForeground(new java.awt.Color(255, 255, 255));
        Contraseña2.setText("Contraseña:");
        getContentPane().add(Contraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        User2.setBackground(new java.awt.Color(0, 0, 0));
        User2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        User2.setForeground(new java.awt.Color(255, 255, 255));
        User2.setText("Usuario:");
        getContentPane().add(User2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        User1.setBackground(new java.awt.Color(0, 0, 0));
        User1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        User1.setForeground(new java.awt.Color(255, 255, 255));
        User1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User1ActionPerformed(evt);
            }
        });
        getContentPane().add(User1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 230, -1));

        Password1.setBackground(new java.awt.Color(0, 0, 0));
        Password1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Password1.setForeground(new java.awt.Color(255, 255, 255));
        Password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password1ActionPerformed(evt);
            }
        });
        getContentPane().add(Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 230, -1));

        Login.setBackground(new java.awt.Color(204, 204, 204));
        Login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Login.setText("Iniciar Sesión");
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Corbel", 3, 24)); // NOI18N
        jLabel2.setText("De la");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Corbel", 3, 24)); // NOI18N
        jLabel1.setText("H. Claustro de Maestros ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 250, 40));

        jLabel3.setFont(new java.awt.Font("Corbel", 3, 24)); // NOI18N
        jLabel3.setText("Facultad de Ingeniería");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blue-desktop-wallpaper.jpg"))); // NOI18N
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void User1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User1ActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add you handling code here:
    }//GEN-LAST:event_LoginActionPerformed

    private void Password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password1ActionPerformed

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        String user = "admin";
        String pass = "uach";
        
        String uPass = new String(Password1.getPassword());
        
        if (User1.getText().equals(user) && uPass.equals(pass)){
            Tabbed home = new Tabbed();
            home.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario y/o contraseña incorrectos");
        }
    }//GEN-LAST:event_LoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contraseña2;
    private javax.swing.JToggleButton Login;
    private javax.swing.JPasswordField Password1;
    private javax.swing.JTextField User1;
    private javax.swing.JLabel User2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
